#**FAKE NEWS CLASSIFIER USING Bidirectional LSTM

In [1]:
import pandas as pd


In [3]:
df =pd.read_csv('/content/FakeNewsNet .csv')

In [4]:
df.head(20)

title  \
0   Kandi Burruss Explodes Over Rape Accusation on...   
1   People's Choice Awards 2018: The best red carp...   
2   Sophia Bush Sends Sweet Birthday Message to 'O...   
3   Colombian singer Maluma sparks rumours of inap...   
4   Gossip Girl 10 Years Later: How Upper East Sid...   
5   Gwen Stefani Got Dumped by Blake Shelton Over ...   
6   Broward County Sheriff Fired For Lying About P...   
7   Amber Rose Shuts Down French Montana Dating Ru...   
8   Mindy Kaling makes first post-baby appearance ...   
9   Katharine McPhee Butchers Tony Nominations: “I...   
10  ‘WAGS Miami’ Stars Ashley Nicole Roberts and P...   
11  Mel Gibson: Hollywood Pedophiles Have Nowhere ...   
12  Medium Tyler Henry Addresses The ‘Chilling’ Me...   
13      DWTS Season 27 Results: Week 5 - Disney Night   
14        2011 via CQ subscribers only Tax Foundation   
15  5 Reasons Why Tarek El Moussa Will Overcome Hi...   
16  David Cassidy cuts estranged daughter Katie co...   
17  Actress Brigitte Nielsen, 54, has given birth ...   
18  The Kardashians donate whopping sum to Las Veg...   
19  Is Brad Pitt Open To Getting Back Together Wit...   

                                             news_url          source_domain  \
0   http://toofab.com/2017/05/08/real-housewives-a...             toofab.com   
1   https://www.today.com/style/see-people-s-choic...          www.today.com   
2   https://www.etonline.com/news/220806_sophia_bu...       www.etonline.com   
3   https://www.dailymail.co.uk/news/article-33655...    www.dailymail.co.uk   
4   https://www.zerchoo.com/entertainment/gossip-g...        www.zerchoo.com   
5   www.intouchweekly.com/posts/gwen-stefani-dumpe...  www.intouchweekly.com   
6   https://yournewswire.com/broward-county-sherif...       yournewswire.com   
7   www.etonline.com/news/214798_amber_rose_shuts_...       www.etonline.com   
8   https://www.aol.com/article/entertainment/2018...            www.aol.com   
9   https://www.98online.com/2018/05/02/katharine-...       www.98online.com   
10  https://www.usmagazine.com/celebrity-news/news...     www.usmagazine.com   
11  yournewswire.com/mel-gibson-hollywood-pedophiles/       yournewswire.com   
12  https://perezhilton.com/tyler-henry-says-krist...        perezhilton.com   
13  https://abc.go.com/shows/dancing-with-the-star...             abc.go.com   
14                                                NaN                    NaN   
15  www.eonline.com/news/932478/5-reasons-why-tare...        www.eonline.com   
16  https://www.thesun.co.uk/news/5086439/david-ca...       www.thesun.co.uk   
17  https://www.usatoday.com/story/life/people/201...       www.usatoday.com   
18  https://web.archive.org/web/20171228144534/htt...        web.archive.org   
19  hollywoodlife.com/2017/08/27/would-brad-pitt-g...      hollywoodlife.com   

    tweet_num  real  
0          42     1  
1           0     1  
2          63     1  
3          20     1  
4          38     1  
5          45     0  
6         124     0  
7           4     0  
8          59     1  
9          10     1  
10         18     1  
11         95     0  
12          4     1  
13          0     1  
14          0     1  
15         63     0  
16         54     1  
17         64     1  
18          1     0  
19         19     0

In [5]:
df.tail()

title  \
23191  Pippa Middleton wedding: In case you missed it...   
23192  Zayn Malik & Gigi Hadid’s Shocking Split: Why ...   
23193  Jessica Chastain Recalls the Moment Her Mother...   
23194  Tristan Thompson Feels "Dumped" After Khloé Ka...   
23195  Kelly Clarkson Performs a Medley of Kendrick L...   

                                                news_url  \
23191  https://www.express.co.uk/news/royal/807049/pi...   
23192  hollywoodlife.com/2018/03/13/zayn-malik-gigi-h...   
23193  http://www.justjared.com/2018/01/17/jessica-ch...   
23194  www.intouchweekly.com/posts/tristan-thompson-f...   
23195  https://www.billboard.com/articles/news/bbma/8...   

               source_domain  tweet_num  real  
23191      www.express.co.uk         52     1  
23192      hollywoodlife.com          7     0  
23193      www.justjared.com         26     1  
23194  www.intouchweekly.com         24     0  
23195      www.billboard.com         85     1

In [6]:
df.shape

(23196, 5)

In [7]:
df.isnull().sum()

title              0
news_url         330
source_domain    330
tweet_num          0
real               0
dtype: int64

In [8]:
#dropping the null values
df = df.dropna()

In [9]:
df.head()

title  \
0  Kandi Burruss Explodes Over Rape Accusation on...   
1  People's Choice Awards 2018: The best red carp...   
2  Sophia Bush Sends Sweet Birthday Message to 'O...   
3  Colombian singer Maluma sparks rumours of inap...   
4  Gossip Girl 10 Years Later: How Upper East Sid...   

                                            news_url        source_domain  \
0  http://toofab.com/2017/05/08/real-housewives-a...           toofab.com   
1  https://www.today.com/style/see-people-s-choic...        www.today.com   
2  https://www.etonline.com/news/220806_sophia_bu...     www.etonline.com   
3  https://www.dailymail.co.uk/news/article-33655...  www.dailymail.co.uk   
4  https://www.zerchoo.com/entertainment/gossip-g...      www.zerchoo.com   

   tweet_num  real  
0         42     1  
1          0     1  
2         63     1  
3         20     1  
4         38     1

In [10]:
# getting the independence feature
x= df.drop('real', axis=1)

In [11]:
y= df['real']

In [12]:
df.shape

(22866, 5)

In [13]:
y.shape

(22866,)

In [14]:
import tensorflow as tf


In [15]:
tf.__version__

'2.19.0'

In [16]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional

In [17]:
voc_size=1000

one hot encoding


In [18]:
message =x.copy()

In [19]:
message['title'][1]

"People's Choice Awards 2018: The best red carpet looks"

In [20]:
message

title  \
0      Kandi Burruss Explodes Over Rape Accusation on...   
1      People's Choice Awards 2018: The best red carp...   
2      Sophia Bush Sends Sweet Birthday Message to 'O...   
3      Colombian singer Maluma sparks rumours of inap...   
4      Gossip Girl 10 Years Later: How Upper East Sid...   
...                                                  ...   
23191  Pippa Middleton wedding: In case you missed it...   
23192  Zayn Malik & Gigi Hadid’s Shocking Split: Why ...   
23193  Jessica Chastain Recalls the Moment Her Mother...   
23194  Tristan Thompson Feels "Dumped" After Khloé Ka...   
23195  Kelly Clarkson Performs a Medley of Kendrick L...   

                                                news_url  \
0      http://toofab.com/2017/05/08/real-housewives-a...   
1      https://www.today.com/style/see-people-s-choic...   
2      https://www.etonline.com/news/220806_sophia_bu...   
3      https://www.dailymail.co.uk/news/article-33655...   
4      https://www.zerchoo.com/entertainment/gossip-g...   
...                                                  ...   
23191  https://www.express.co.uk/news/royal/807049/pi...   
23192  hollywoodlife.com/2018/03/13/zayn-malik-gigi-h...   
23193  http://www.justjared.com/2018/01/17/jessica-ch...   
23194  www.intouchweekly.com/posts/tristan-thompson-f...   
23195  https://www.billboard.com/articles/news/bbma/8...   

               source_domain  tweet_num  
0                 toofab.com         42  
1              www.today.com          0  
2           www.etonline.com         63  
3        www.dailymail.co.uk         20  
4            www.zerchoo.com         38  
...                      ...        ...  
23191      www.express.co.uk         52  
23192      hollywoodlife.com          7  
23193      www.justjared.com         26  
23194  www.intouchweekly.com         24  
23195      www.billboard.com         85  

[22866 rows x 4 columns]

In [21]:
import nltk
import re
from nltk.corpus import stopwords

In [22]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [23]:
# data preprocessing

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus =[]
message = message.reset_index(drop=True) # Reset index after dropping nulls
for i in range(0,len(message)):
  review =re.sub('[^a-zA-Z]', ' ', message['title'][i])
  review = review.lower()
  review = review.split()


  review =[ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

In [24]:
corpus

['kandi burruss explod rape accus real housew atlanta reunion video',
 'peopl choic award best red carpet look',
 'sophia bush send sweet birthday messag one tree hill co star hilari burton breyton eva',
 'colombian singer maluma spark rumour inappropri relationship aunt',
 'gossip girl year later upper east sider shock world chang pop cultur forev',
 'gwen stefani got dump blake shelton jealousi drama exclus',
 'broward counti sheriff fire lie parkland',
 'amber rose shut french montana date rumor call rapper bruvaaa',
 'mindi kale make first post babi appear disneyland wrinkl time co star',
 'katharin mcphee butcher toni nomin drink',
 'wag miami star ashley nicol robert philip wheeler marri',
 'mel gibson hollywood pedophil nowher left hide',
 'medium tyler henri address chill messag kristin cavallari deceas brother express read',
 'dwt season result week disney night',
 'reason tarek el moussa overcom latest back injuri',
 'david cassidi cut estrang daughter kati complet leav son b

In [25]:
corpus[1]

'peopl choic award best red carpet look'

In [26]:
onehot_repr = [one_hot(words,voc_size) for words in corpus]
onehot_repr

[[251, 139, 119, 916, 263, 106, 83, 187, 885, 336],
 [10, 132, 315, 728, 266, 803, 31],
 [615, 772, 857, 626, 62, 890, 982, 781, 570, 997, 648, 87, 257, 825, 39],
 [429, 634, 450, 335, 440, 676, 611, 890],
 [4, 349, 968, 209, 808, 50, 592, 69, 58, 872, 256, 957, 886],
 [446, 628, 97, 572, 537, 320, 137, 923, 613],
 [938, 500, 867, 514, 645, 768],
 [394, 888, 951, 442, 413, 441, 363, 238, 196, 551],
 [158, 169, 433, 597, 768, 260, 311, 421, 810, 274, 997, 648],
 [482, 344, 566, 853, 228, 113],
 [840, 543, 648, 644, 449, 415, 338, 465, 653],
 [131, 823, 727, 286, 905, 159, 767],
 [51, 984, 886, 943, 814, 890, 827, 984, 628, 946, 888, 844],
 [29, 249, 401, 391, 991, 749],
 [510, 219, 260, 710, 327, 785, 132, 880],
 [36, 470, 691, 334, 90, 25, 228, 315, 510, 995],
 [343, 953, 599, 553, 294, 999, 211],
 [721, 711, 34, 800, 629, 308, 549, 109, 314],
 [87, 312, 40, 422, 132, 222, 802, 363],
 [883, 392, 268, 128, 968, 781],
 [596, 611, 243, 318, 449, 568, 86, 157, 86, 562, 405, 246, 445],
 [60

In [27]:
onehot_repr[1]

[10, 132, 315, 728, 266, 803, 31]

  embedding represntation

In [28]:
sent_length=20
embedded_docs =pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[  0   0   0 ... 187 885 336]
 [  0   0   0 ... 266 803  31]
 [  0   0   0 ... 257 825  39]
 ...
 [  0   0   0 ... 562 679 852]
 [  0   0   0 ... 629   3 613]
 [  0   0   0 ... 671 971 315]]


In [29]:
embedded_docs[1]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
        10, 132, 315, 728, 266, 803,  31], dtype=int32)

# CREATING THE MODEL

In [30]:
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Bidirectional(LSTM(100)))
model.add(Dense(1,activation='sigmoid'))
model.build(input_shape=(None, sent_length))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 20, 40)         │        40,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ (None, 200)            │       112,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │           201 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 153,001 (597.66 KB)

 Trainable params: 153,001 (597.66 KB)

 Non-trainable params: 0 (0.00 B)

None


In [31]:
len(embedded_docs), y.shape

(22866, (22866,))

In [32]:
import numpy as np
x_final =np.array(embedded_docs)
y_final =np.array(y)

In [33]:
x_final.shape, y_final.shape

((22866, 20), (22866,))

In [34]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_final,y_final, test_size=0.33, random_state=42)

In [35]:
##finally taining the model
model.fit(x_train,y_train, validation_data=(x_test,y_test), epochs=10, batch_size=64)

Epoch 1/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 7s 13ms/step - accuracy: 0.7696 - loss: 0.5368 - val_accuracy: 0.8149 - val_loss: 0.4373
Epoch 2/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.8196 - loss: 0.4144 - val_accuracy: 0.8162 - val_loss: 0.4315
Epoch 3/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8314 - loss: 0.3945 - val_accuracy: 0.8169 - val_loss: 0.4331
Epoch 4/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.8367 - loss: 0.3792 - val_accuracy: 0.8147 - val_loss: 0.4353
Epoch 5/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8486 - loss: 0.3598 - val_accuracy: 0.8077 - val_loss: 0.4487
Epoch 6/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8539 - loss: 0.3393 - val_accuracy: 0.8069 - val_loss: 0.4552
Epoch 7/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8580 - loss: 0.3337 - val_accuracy: 0.8057 - val_loss: 0.4750
Epoch 8/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8582 - loss: 0.3294 - val_accuracy: 

# PERFORMANCE METICS AND ACCURACY

In [36]:
y_pred = model.predict(x_test)


236/236 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step


In [37]:
y_pred =np.where(y_pred>0.5,1,0) #AUC ROC CURVE


In [38]:
from sklearn.metrics import confusion_matrix

In [39]:
confusion_matrix(y_test,y_pred)

array([[ 951,  891],
       [ 682, 5022]])

In [40]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7915451895043731

In [41]:
from sklearn.metrics import accuracy_score,classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.58      0.52      0.55      1842
           1       0.85      0.88      0.86      5704

    accuracy                           0.79      7546
   macro avg       0.72      0.70      0.71      7546
weighted avg       0.78      0.79      0.79      7546

